config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root   'pages#home'
  get    'users/adminsettings'
  get    'schedules/workschedule'
  get    'schedules/requestschedule'
  get    'schedules/approveschedule'
  get    'schedules/editschedule'
  get    'schedules/originalschedule'
  patch  'schedules/:id/update_to_edit_schedule' => 'schedules#update_to_edit_schedule'
  patch  'users/:id/update_to_comment'   => 'users#update_to_comment'
  post   'users/:id/update_confirmed_at' => 'users#update_confirmed_at'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/guest_admin_sign_in', to: 'users/sessions#new_guest_admin'
    get 'users/paying_user_sign_in', to: 'users/registrations#new_paying'
  end

  resources :users, :only => [:update, :destroy] # adminsettings用
  resources :schedules
  resources :stores
  resources :schedule_checkboxes
  resources :inquiries

  resources :payments, only: [:new]
  get '/payments/after_payment_register', controller: 'payments', action: 'after_payment_register'
  get '/payments/payment_cancel', controller: 'payments', action: 'payment_cancel'

end

app/views/shared/_calender_count_schedule.html.erb
<%# 申請シフトを時間枠ごとにカウント（不足シフト確認用）%>
<% @timezones.each_with_index do |timezone,i| %><%# "A"はTimezoneTableからEach.doで取り出し%>
  <tr>
    <th><%= timezone %>申請数</th>
    <% @beginningtoendday.each do |day| %>
      <td><%= countschedule_check(@user_and_schedules_first_schedules_first.store_id, day, timezone, @searched_approved) %></td>
    <% end %>
    <% if i == 0 %>
      <th class="user-salary"><%= salary_calculation_of_store(@searched_store, @beginningday, @endday, @searched_approved) %></th>
    <% end %>
  </tr>
<% end %>

app/views/shared/_calender_storename_datepart.html.erb
<%# 店名 %>
<tr>
  <th><%= @user_and_schedules_first.schedules.first.store.storename %></th>
</tr>

<%# 日付 %>
<tr>
  <th><%= @beginningday.strftime("%Y/%m").to_s %></th>
  <% @beginningtoendday.each do |day| %>
    <% if day == Date.current %>
      <!-- 当日はオレンジ色に -->
      <th style="background-color:rgb(255, 201, 101);color:black;"><%= day.strftime("%d").to_s %></th>
    <% else %>
      <th><%= day.strftime("%d").to_s %></th>
    <% end %>
  <% end %>
</tr>

<%# 月初から月末まで曜日を表示%>
<tr>
  <th>曜日</th>
  <% @beginningtoendday.each do |day| %>
    <% if day == Date.current %>
      <!-- 当日はオレンジ色に -->
      <th style="background-color:rgb(255, 201, 101);color:black;">
        <% if day.strftime("%a").to_s == "Sun" %><div class="sunday" style="color:black !important;">日</div><% end %>
        <% if day.strftime("%a").to_s == "Mon" %>月<% end %>
        <% if day.strftime("%a").to_s == "Tue" %>火<% end %>
        <% if day.strftime("%a").to_s == "Wed" %>水<% end %>
        <% if day.strftime("%a").to_s == "Thu" %>木<% end %>
        <% if day.strftime("%a").to_s == "Fri" %>金<% end %>
        <% if day.strftime("%a").to_s == "Sat" %><div class="saturday" style="color:black !important;">土</div><% end %>
      </th>
    <% elsif HolidayJapan.check(day) %>
      <!-- 祝日は日曜日と同じ実装 -->
      <th>
        <% if day.strftime("%a").to_s == "Sun" %><div class="sunday">日</div><% end %>
        <% if day.strftime("%a").to_s == "Mon" %><div class="sunday">月</div><% end %>
        <% if day.strftime("%a").to_s == "Tue" %><div class="sunday">火</div><% end %>
        <% if day.strftime("%a").to_s == "Wed" %><div class="sunday">水</div><% end %>
        <% if day.strftime("%a").to_s == "Thu" %><div class="sunday">木</div><% end %>
        <% if day.strftime("%a").to_s == "Fri" %><div class="sunday">金</div><% end %>
        <% if day.strftime("%a").to_s == "Sat" %><div class="sunday">土</div><% end %>
      </th>
    <% else %>
      <th>
        <% if day.strftime("%a").to_s == "Sun" %><div class="sunday">日</div><% end %>
        <% if day.strftime("%a").to_s == "Mon" %>月<% end %>
        <% if day.strftime("%a").to_s == "Tue" %>火<% end %>
        <% if day.strftime("%a").to_s == "Wed" %>水<% end %>
        <% if day.strftime("%a").to_s == "Thu" %>木<% end %>
        <% if day.strftime("%a").to_s == "Fri" %>金<% end %>
        <% if day.strftime("%a").to_s == "Sat" %><div class="saturday">土</div><% end %>
      </th>
    <% end %>
  <% end %>

  <% unless @visualization == false %><th>給与概算</th><% end %>
  <th>入店時期</th>
  <% unless @visualization == false %><th>コメント</th><% end %>
</tr>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#site-menu">
        <i class="menuicon fas fa-bars" style="color:white;"> MENU </i>
      </button>
      <button type="button" class="navbar-toggle sp-mode" style="display:none;">
        <i class="menuicon fas fa-mobile-alt" style="color:white;"> スマートフォン表示 </i>
      </button>
      <button type="button" class="navbar-toggle pc-mode" style="display:none;">
        <i class="menuicon fas fa-desktop" style="color:white;"> PC表示 </i>
      </button>
      <%= link_to "勤怠管理", root_path, id: "logo", class: "navbar-brand"%>
    </div>
    <div class="collapse navbar-collapse" id="site-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.username,edit_user_registration_path %></li>
          <li><%= link_to "スケジュール一覧",schedules_workschedule_path %></li>
          <li><%= link_to "シフト申請",     schedules_requestschedule_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to "シフト承認",     schedules_approveschedule_path %><%# only admin%></li>
            <li><%= link_to "シフト編集",     schedules_editschedule_path %><%# only admin%></li>
            <li><%= link_to "シフト原本",     schedules_originalschedule_path %><%# only admin%></li>
            <li><%= link_to "管理者用設定",   users_adminsettings_path %><%# only superadmin%></li>
          <% end %>
          <li><%= link_to "ログアウト", destroy_user_session_path,method: :delete %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<script>
  var pc_width = 1080;
  var device = (screen.width < 600 ? 'sp' : 'pc');
  var view_mode = (device == 'pc' || document.cookie.indexOf('view_mode=pc') != -1 ? 'pc' : 'sp');
  if (device == 'sp' && view_mode == 'pc') {
    document.getElementsByName('viewport')[0].setAttribute('content', 'width=' + pc_width + ',initial-scale=1');
  }
  $(function () {
    if (device == 'sp') {
      if (view_mode == 'pc') {
        $('.sp-mode').on('click', function () {
          var date = new Date();
          date.setTime(0);
          document.cookie = 'view_mode=;expires='+date.toGMTString();
          location.reload(false);
        }).show();
      } else {
        $('.pc-mode').on('click', function () {
          document.cookie = 'view_mode=pc';
          location.reload(false);
        }).show();
      }
    }
  });
</script>