config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root   'pages#home'
  get    'users/adminsettings'
  get    'schedules/workschedule'
  get    'schedules/requestschedule'
  get    'schedules/approveschedule'
  get    'schedules/editschedule'
  get    'schedules/originalschedule'
  patch  'schedules/:id/update_to_edit_schedule' => 'schedules#update_to_edit_schedule'
  patch  'users/:id/update_to_comment'   => 'users#update_to_comment'
  post   'users/:id/update_confirmed_at' => 'users#update_confirmed_at'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/guest_admin_sign_in', to: 'users/sessions#new_guest_admin'
    get 'users/paying_user_sign_in', to: 'users/registrations#new_paying'
  end

  resources :users, :only => [:update, :destroy] # adminsettings用
  resources :schedules
  resources :stores
  resources :schedule_checkboxes
  resources :inquiries

  resources :payments, only: [:new]
  get '/payments/after_payment_register', controller: 'payments', action: 'after_payment_register'
  get '/payments/payment_cancel', controller: 'payments', action: 'payment_cancel'

end

app/views/pages/_guest_signup.html.erb
<% unless user_signed_in? %>
  <div class="flex common-justify-content-center">
    <%= link_to 'ゲストログイン（一般権限）', users_guest_sign_in_path, method: :post, class: "btn-lg btn-success guest-login" %>
    <%= link_to 'ゲストログイン（店長権限）', users_guest_admin_sign_in_path, method: :post, class: "btn-lg btn-success guest-login" %>
  </div>
<% end %>
<br>

app/views/pages/_inquiry.html.erb
<% if user_signed_in? %>
  <div class="flex common-justify-content-center">
    <%= bootstrap_form_with(model: @inquiry, local: true) do |f| %>
      <%= f.label :アプリ改善要望欄 %>
      <p>例：この機能を改善して欲しい〜など</p>
      <%= f.text_area :request_comment, :size => "80x2", hide_label: true %>
      <%= f.submit "送信", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>
<br>

app/views/pages/_signup.html.erb
<% unless user_signed_in? %>
  <div class="flex common-justify-content-center">
    <%= link_to "新規登録", new_user_registration_path, class: "btn btn-lg btn-primary" %>
    &nbsp;&nbsp;&nbsp;
    <%= link_to "ログイン", new_user_session_path, class: "btn btn-lg btn-primary" %>
  </div>
  <br>
  <%= link_to "管理者新規登録", users_paying_user_sign_in_path, class: "btn btn-lg btn-primary" %>
<% end %>
<br>

app/views/pages/_tutorial.html.erb
<!DOCTYPE html>
<html>
<head>
<title>tutorial.md</title>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8">

<style>

img {
	max-width: 100%;
	max-height: 100%;
}

</style>

<script src="https://unpkg.com/mermaid/dist/mermaid.min.js"></script>
</head>
<body>
  <script>
    mermaid.initialize({
      startOnLoad: true,
      theme: document.body.classList.contains('vscode-dark') || document.body.classList.contains('vscode-high-contrast')
          ? 'dark'
          : 'default'
    });
  </script>
<h1 id="%E6%A6%82%E8%A6%81">概要</h1>
<p>シフト表作成者の業務改善ための勤怠管理アプリです。<br />
従業員ユーザが勤怠管理アプリにシフトを申請し、店長ユーザが申請されたシフトを一元管理できます。<br />
従業員個別に希望シフトをヒヤリングして、Excelでシフト表を作成する手間を無くし、<br />
シフト作成業務に割く時間を軽減できます。</p>
<h1 id="%E4%BD%BF%E3%81%84%E6%96%B9">使い方</h1>
<ol>
<li>シフトの申請</li>
</ol>
<ul>
<li>シフト申請先店舗を、申請日、勤務時間帯を選択してシフト申請することが出来ます。</li>
<li>申請したシフトは右欄「申請済みシフト欄」で検索が可能です。</li>
<li>申請直後のシフトは「未承認」の状態になっていますが、店長権限者が当該シフトを承認後に「承認済」に変化します。</li>
<li>なお、店長権限者は他ユーザのシフトの申請、検索、承認可否の選択が可能です。</li>
<li>さらに、「その他要望」欄では店長向けの要望、コメントを記入することが可能です。
<a href="https://gyazo.com/d69df741220bcee5b4b9cf333642852f"><img src="https://i.gyazo.com/d69df741220bcee5b4b9cf333642852f.png" alt="Image from Gyazo"></a>
<a href="https://gyazo.com/2c62156534acb532c2cdd9e9b8721ba9"><img src="https://i.gyazo.com/2c62156534acb532c2cdd9e9b8721ba9.png" alt="Image from Gyazo"></a></li>
</ul>
<ol start="2">
<li>スケジュール一覧ページ</li>
</ol>
<ul>
<li>承認済のシフトのみ表示されます。</li>
<li>店舗、期間を選択してスケジュールの一覧を表示します。</li>
<li>ユーザの表示順はユーザ登録時に設定する、「主な勤務時間帯」順になっています。</li>
<li>勤務時間帯に応じてユーザ欄が色分けされます。</li>
<li>画面全体をキャプチャし、PNG画像出力が可能です。（PC限定限定）
<a href="https://gyazo.com/24b8a263c0c6fa56bb91976143c7e758"><img src="https://i.gyazo.com/24b8a263c0c6fa56bb91976143c7e758.png" alt="Image from Gyazo"></a></li>
</ul>
<ol start="3">
<li>シフト承認ページ（店長権限のみ使用可）</li>
</ol>
<ul>
<li>申請されたシフトが表示されます。</li>
<li>シフトをクリックすると、「未承認」⇔「承認済」の切り替えが可能です。</li>
<li>未承認のシフトはグレー、承認済のシフトは黒文字で表示されます。</li>
<li>ユーザ行下部にシフト申請項目ごとのカウンタがあり、同時刻にいくつシフトが申請されたか確認が可能です。</li>
<li>シフト表右欄には各ユーザからの要望コメントが表示されます。
<a href="https://gyazo.com/cd6207eb423285777201456cf10ca769"><img src="https://i.gyazo.com/cd6207eb423285777201456cf10ca769.png" alt="Image from Gyazo"></a>
<a href="https://gyazo.com/e50e9b3ea51dea74abbb1a2e5e34ea3c"><img src="https://i.gyazo.com/e50e9b3ea51dea74abbb1a2e5e34ea3c.png" alt="Image from Gyazo"></a></li>
</ul>
<ol start="4">
<li>シフト編集ページ（店長権限のみ使用可）</li>
</ol>
<ul>
<li>主な機能は「シフト承認ページ」と同じですが、変更点は以下の通りです。</li>
<li>シフトをクリックするとモーダルウィンドウが表示され、シフトの編集・削除が出来ます。
<a href="https://gyazo.com/4203a4b0c58acf0ecc4cb4ee67b2e08e"><img src="https://i.gyazo.com/4203a4b0c58acf0ecc4cb4ee67b2e08e.png" alt="Image from Gyazo"></a></li>
</ul>
<ol start="5">
<li>管理者用設定（店長権限のみ使用可）</li>
</ol>
<ul>
<li>店舗、シフト申請項目追加、ユーザ情報編集が出来ます。</li>
<li>ユーザ情報編集では、「一般ユーザ」⇔「店長ユーザ（管理者）」の権限切替、<br>
新規ユーザのログイン許可、アカウント削除が可能です。
<a href="https://gyazo.com/2ebf82fffbdc6fa009b98ab09c12ba38"><img src="https://i.gyazo.com/2ebf82fffbdc6fa009b98ab09c12ba38.png" alt="Image from Gyazo"></a></li>
</ul>
<h1 id="%E6%A9%9F%E8%83%BD%E4%B8%80%E8%A6%A7">機能一覧</h1>
<ul>
<li>
<p>ユーザ関連</p>
<ul>
<li>新規登録</li>
<li>ログイン</li>
<li>ログアウト</li>
<li>プロフィール表示、編集</li>
<li>基本勤務時間帯の登録</li>
</ul>
</li>
<li>
<p>シフト系</p>
<ul>
<li>申請（複数日付に一括申請可能、予め登録された勤務時間帯のチェックボックスを選択し複数店舗に申請できる）</li>
<li>削除</li>
<li>承認（管理者ユーザ限定、シフト表の申請済シフトをクリックで承認可否を切替）</li>
<li>編集（管理者ユーザ限定、シフト表の申請済シフトをクリックでモーダルウィンドウを表示、承認可否の切替、申請内容変更、削除）</li>
<li>シフトの検索、絞り込み機能（ユーザ名、店舗名、申請日、承認可否）</li>
<li>確定シフト表の表示（月単位）</li>
<li>確定シフト表のPNG画像出力</li>
<li>勤務時間帯順でシフト表のユーザ表示順をソート</li>
<li>時間帯ごとのシフト申請数をカウント（時間帯ごとに必要な人員数があるので見える化）</li>
</ul>
</li>
<li>
<p>管理者設定系</p>
<ul>
<li>店舗追加（フランチャイズでは複数店舗を経営することがあるので必要）</li>
<li>勤務時間帯項目追加（シフト申請用のチェックボックスの追加）</li>
<li>ログイン許可機能（新規ユーザログイン許可に使用）</li>
<li>他ユーザの権限変更（従業員ユーザ⇔店長ユーザ）</li>
<li>他ユーザの削除（退職者アカウントの削除）</li>
</ul>
</li>
<li>
<p>その他</p>
<ul>
<li>レスポンシブ対応</li>
<li>Ajax化（シフト作成・承認・編集・削除、新規ユーザログイン許可・権限変更・削除で使用）</li>
<li>FlashのToast化</li>
<li>静的コード解析ツール導入（Rubocop）</li>
<li>ゲストユーザー機能（編集不可ロジック組込み済）</li>
<li>MultiDatespicker導入 (シフト申請、複数日付への一括申請に使用)</li>
</ul>
</li>
</ul>
<h1 id="%E4%BD%BF%E7%94%A8%E6%8A%80%E8%A1%93">使用技術</h1>
<ul>
<li>HTML</li>
<li>CSS / Bootstrap</li>
<li>JavaScript / jQuery / Ajax</li>
<li>Ruby 2.7.3</li>
<li>Ruby on Rails 6.0.3.2</li>
<li>nginx（Webサーバ）</li>
<li>Puma（アプリケーションサーバ）</li>
<li>Git / GitHub</li>
<li>AWS(VPC,ECS,Route53,ACM,ALB,IAM,RDS for MySQL 5.7)</li>
<li>Docker / Docker-compose</li>
<li>CircleCI</li>
<li>RSpec</li>
</ul>
<h1 id="aws%E6%A7%8B%E6%88%90%E5%9B%B3">AWS構成図</h1>
<p><a href="https://gyazo.com/b1e07f086d67a8c83cbf9c0174decb7f"><img src="https://i.gyazo.com/b1e07f086d67a8c83cbf9c0174decb7f.png" alt="Image from Gyazo"></a></p>
<h1 id="er%E5%9B%B3">ER図</h1>
<p><a href="https://gyazo.com/cfea68de619124993f97e330faa966f7"><img src="https://i.gyazo.com/cfea68de619124993f97e330faa966f7.png" alt="Image from Gyazo"></a></p>

</body>
</html>

app/views/pages/_update_log.html.erb
<% if user_signed_in? %>
  <div class="">
    <h3>お知らせ</h3>
    <p style="text-align:left;">
      2021/05/17
      <br>
      ・シフト申請ページ、スケジュール一覧ページの表示を調整しました。
      <br>
      ・シフト一覧ページを祝日対応しました。
      <br>
      ・提出したシフトの原本をシフト申請履歴から確認できるようにしました。
      <br>
      ・ユーザ新規作成時、ログイン許可時のメール通知機能を作成しました。
      <br>
      <br>
      2021/04/07
      <br>
      ・祝日対応しました。（スケジュール一覧ページ、シフト承認ページ※、シフト編集ページ※、シフト原本ページ※） ※管理者専用
      <br>
      <br>
      2021/03/19
      <br>
      ・シフト申請のチェックボックスが押下できない問題を修正しました。
      <br>
      ・ナビゲーションバーのボタン幅を調整しました。
      <br>
      <br>
      2021/03/03
      <br>
      ・フラッシュメッセージ出現時にMENUと重なってしまう現象を修正しました。
      <br>
      ・新規登録ボタンの横にログインボタンを追加しました。
      <br>
      ・シフト申請ボタン位置を調整しました。（スマートフォンのみ）
      <br>
      ・サイトアイコンを変更しました。（ブックマーク時のアイコン等）
      <br>
      <br>
      2021/02/24
      <br>
      ・カレンダーの今日の日付の色を変更しました。
      <br>
      ・ボタンの色を修正しました。
      <br>
      <br>
      2021/02/17
      <br>
      ・スマートフォンで当サイト使用時、画面上部に「PC表示」、「スマートフォン表示」のボタンを追加しました。
      <br>
      ・PC表示にすると画面の縮小が可能になります。
      <br>
      <br>
      2021/02/13
      <br>
      ・入店日付を2010年から選択できるようにしました。
      <br>
      ・カレンダーの並び順を修正しました。（エクセルのシフト表と同じ形に修正。入店日付昇順に設定。）
      <br>
    </p>
  </div>
<% end %>
<br>

app/views/pages/addstores.html.erb
<% provide(:title, "店舗追加") %>
<div class="row">
  <div class="col-md-6">
    <%= form_for @store do |f| %>
      <div class="field">
        <%= f.label :追加する店舗名を入力してください %><br />
        <%= f.text_field :storename %>
      </div>
      <%= f.submit "追加", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-md-6">
    <h3>追加済み店舗一覧</h3>
    <div>
      <table class="table-bordered table-striped table-responsive">
        <tr>
          <th>店舗</th>
        </tr>
        <% @stores.each do |store| %>
          <tr class="stores">
            <td><%= store.storename%></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/pages/approveschedule.html.erb
<% provide(:title, "シフト承認") %>
<div class="row">
  <div class="col-md-6">
    <p>店舗選択</p>
    <p>従業員選択</p>
    <p>年月日選択</p>
    <p>承認者選択（admin権限ユーザ選択）</p>
  </div>
  <div class="col-md-6">
    <h3>申請されたシフト欄</h3>
    <div>
      <table class="table-bordered table-striped table-responsive">
        <tr>
          <th>申請者</th>
          <th>店舗</th>
          <th>申請日</th>
          <th>申請時間帯</th>
          <th>承認可否</th>
        </tr>
        <% @schedules.each do |schedule| %>
          <tr class="schedules_<%= schedule.id %>">
            <%= render partial: "pages/approve", locals: { schedule: schedule} %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% provide(:title, "ホーム") %>
<div class="container">
  <%= render partial: "pages/inquiry" %>
  <%= render partial: "pages/update_log" %>
  <div class="center jumbotron">
    <%= render partial: "pages/signup" %>
  <br>
    <% if current_user.present? %>
      <%= link_to "料金プラン変更", new_payment_path, class: "btn btn-lg btn-primary" %>
      <%# subscription = Stripe::Subscription.retrieve(current_user.plan_id) %>
      <%#= subscription.status %>
      <p><%#= "有料プランです" if subscription.plan.amount > 0 %></p>
    <% end %>
    <% if Rails.env.development? %>
      <%= render partial: "pages/guest_signup" %>
    <% end %>
    <p class="toppage-font">パソコン、スマートフォンからシフト申請ができるサイトです。</p><br>
    <div class="row">
      <div class="col-md-8"><%= image_tag 'calender.png' ,style: "width: 100%;"%></div>
      <div class="col-md-4"><p class="toppage-font"><br>店舗ごとのシフト状況がひと目でわかる！</p></div>
    </div>
    <br>
    <br>
    <br>
    <div class="row">
      <div class="col-md-4"><p class="toppage-font"><br>シフトの申請も簡単に！<br>申請したシフトも一覧で確認！</p></div>
      <div class="col-md-8"><%= image_tag 'request.png' ,style: "width: 100%;"%></div>
    </div>
  </div>
  <%#= render partial: "pages/tutorial" %>
</div>

app/views/pages/requestschedule.html.erb
<% provide(:title, "シフト申請") %>
<div class="row">
  <div class="col-md-6">
    <%= form_with model: @requestschedule, local: true  do |f| %>
    <%#formwith完成形はremote trueにしてAjax処理にする form_with model: @requestschedule do |f| %>
      <h3>シフト申請</h3>
      <p>■シフト申請者：<%= current_user.username %></p>

      <div class="field">
        <%= f.label :シフト申請先店舗 %><br />
        <%= f.collection_select :store_id, Store.all, :id, :storename %>
      </div>
      <p>■カレンダーからシフト申請する日を選択してください</p>
      <div class="field">
        <%= f.label :シフト申請日 %><br />
        <%= f.date_field :request_day %>
      </div>
      <div class="field request_timezone">
        <%= f.label :シフト勤務時間帯 %><br />
         ★Aとかの右の時間帯の部分は別枠に移動する？店舗ごとに差異があるので
        <p>A  (06:00-09:00): <%= f.check_box :request_timezone ,{ multiple: true }, "A" , nil %></p>
        <p>B  (09:00-13:00): <%= f.check_box :request_timezone ,{ multiple: true }, "B" , nil %></p>
        <p>C  (13:00-17:00): <%= f.check_box :request_timezone ,{ multiple: true }, "C" , nil %></p>
        <p>D  (17:00-21:00): <%= f.check_box :request_timezone ,{ multiple: true }, "D" , nil %></p>
        <p>E1 (21:00-01:00): <%= f.check_box :request_timezone ,{ multiple: true }, "E1", nil %></p>
        <p>E3 (21:00-03:00): <%= f.check_box :request_timezone ,{ multiple: true }, "E3", nil %></p>
        <p>E  (21:00-06:00): <%= f.check_box :request_timezone ,{ multiple: true }, "E" , nil %></p>
      </div>
      <p>■チェックボックス外の時間を申請する場合は下記に時間を入力してください。</p>
      <div class="field">
        <%= f.label :シフト申請時間（開始） %>
        <%= f.select :request_start_time, ['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23'], {include_blank: true} %>時
      </div>
      <div class="field">
        <%= f.label :シフト申請時間（終了） %>
        <%= f.select :request_end_time,   ['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23'], {include_blank: true} %>時
      </div>

      <p>■指定したシフトを確認後、申請ボタンを押してください。</p>
      <%= f.submit "シフト申請", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-md-6">
    <h3>申請済みシフト欄</h3>
    <div>
      <p>★ここに申請済みシフトをDBから一覧表示（Micropostsを参考に,承認されたやつだけマークつける）</p>
      <p>★申請したシフトは年月で検索可能、申請時間の横にどの店のシフトかも表示</p>
      <table class="schtable table-bordered table-striped table-responsive">
        <tr>
          <th>申請者</th>
          <th>店舗</th>
          <th>申請日</th>
          <th>申請時間帯</th>
          <th>承認可否</th>
        </tr>
        <% @schedules.each do |schedule| %>
          <tr class="schedules_<%= schedule.id %>">
            <%= render partial: "pages/request", locals: { schedule: schedule} %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>